name: Kide
description: A KIIT guide you'd want to use.
version: 2.1.1+49

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^0.18.1
  provider: ^4.0.2
  flutter_staggered_grid_view: ^0.3.0
  url_launcher: ^5.5.0
  shared_preferences: ^0.5.4+6
  google_maps_flutter: ^0.5.11
  geolocator: ^5.1.4+2
  permission_handler: null
  cloud_firestore: ^0.13.0+1
  connectivity: ^0.4.6+2
  location: null
  transparent_image: ^1.0.0
  cached_network_image: null
  dynamic_theme: null
  intl: null
  sqflite: null
  flare_flutter: null
  firebase_auth: null
  firebase_dynamic_links: ^0.5.1
  share: ^0.6.4+3
  day_night_switcher: null
  webview_flutter: null
  fluttertoast: null
  fl_chart: ^0.11.1
  flutter_bcrypt: null
  flutter_email_sender: null
  curved_navigation_bar: ^0.3.2
  onesignal_flutter: ^2.6.1

dev_dependencies:
  flutter_launcher_icons: ^0.7.4
  flutter_test:
    sdk: flutter

flutter_icons:
  android: true
  image_path: "./lib/assets/Icon/kide_logoxxxhdpi.png"

flutter:
  uses-material-design: true

  assets:
    - ./lib/assets/fire.svg
    - ./lib/assets/police.svg
    - ./lib/assets/pharmacy.svg
    - ./lib/assets/Icon/kide_logoldpi.png
    - ./lib/assets/Icon/kide_logoxxxhdpi.png
    - ./lib/assets/maps.png
    - ./lib/assets/contact.png
    - ./lib/assets/AOG-Logo.png
    - ./lib/assets/events.png
    - ./lib/assets/KIIT.jpg
    - ./lib/assets/KISS.png
    - ./lib/assets/Founder_sir.jpeg
    - ./lib/assets/image-placeholder.png
    - ./lib/assets/flares/LoginPage.flr
    - ./lib/assets/

  fonts:
    - family: Quicksand
      fonts:
        - asset: ./lib/fonts/Quicksand/Quicksand-Bold.ttf
        - asset: ./lib/fonts/Quicksand/Quicksand-Light.ttf
        - asset: ./lib/fonts/Quicksand/Quicksand-Medium.ttf
        - asset: ./lib/fonts/Quicksand/Quicksand-Regular.ttf
        - asset: ./lib/fonts/Quicksand/Quicksand-SemiBold.ttf

    - family: PlayfairDisplay
      fonts:
        - asset: ./lib/fonts/PlayfairDisplay/PlayfairDisplay-Bold.otf
        - asset: ./lib/fonts/PlayfairDisplay/PlayfairDisplay-Regular.otf
        - asset: ./lib/fonts/PlayfairDisplay/PlayfairDisplay-Black.otf
        - asset: ./lib/fonts/PlayfairDisplay/PlayfairDisplaySC-Black.otf
        - asset: ./lib/fonts/PlayfairDisplay/PlayfairDisplaySC-Bold.otf

    - family: EncodeSans
      fonts:
        - asset: ./lib/fonts/EncodeSans/EncodeSans-Black.ttf
        - asset: ./lib/fonts/EncodeSans/EncodeSans-Regular.ttf
        - asset: ./lib/fonts/EncodeSans/EncodeSans-Thin.ttf
        - asset: ./lib/fonts/EncodeSans/EncodeSans-Light.ttf
        - asset: ./lib/fonts/EncodeSans/EncodeSans-Medium.ttf
        - asset: ./lib/fonts/EncodeSans/EncodeSans-ExtraLight.ttf

    - family: Michroma
      fonts:
        - asset: ./lib/fonts/Michroma/Michroma-Regular.ttf
